# Generated by Django 4.2.6 on 2023-10-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
